const Data = {

    'Language': ['English', 'French', 'Spanish', 'German', 'Italian', 'Japanese', 'Russian', 'Mandarin', 'Hindi', 'Portuguese', 'Swedish', 'Cantonese', 'Arabic', 'Korean', 'Finnish', 'Polish', 'Dutch', 'Danish', 'Hebrew', 'Latin', 'Turkish', 'Greek', 'Hungarian', 'Persian', 'Norwegian', 'Czech', 'Romanian', 'Thai', 'Tamil', 'Serbian', 'Vietnamese', 'Urdu', 'Chinese', 'Icelandic', 'Serbo-Croatian', 'Telugu', 'Yiddish', 'Tagalog', 'Catalan', 'Bengali', 'Filipino', 'Ukrainian', 'Croatian', 'American Sign Language', 'Indonesian', 'Afrikaans', 'Min Nan', 'Panjabi', 'Estonian', 'Swiss German', 'Flemish', 'Albanian', 'Georgian', 'Swahili', 'Bulgarian', 'Slovak', 'Kurdish', 'Marathi', 'Lithuanian', 'Irish', 'Bosnian', 'Zulu', 'Slovenian', 'Romany', 'Malayalam', 'Pushto', 'Shanghainese', 'Tibetan', 'Xhosa', 'Latvian', 'Armenian', 'Malay', 'Scottish Gaelic', 'Hokkien', 'Inuktitut', 'Klingon', 'Dari', 'Wolof', 'Aboriginal', 'Macedonian', 'Mongolian', 'Hawaiian', 'Gujarati', 'Khmer', 'Quechua', 'Navajo', 'Sioux', 'Chechen', 'Kazakh', 'Maori', 'Welsh', 'Neapolitan', 'Saami', 'Sicilian', 'Basque', 'Azerbaijani', 'Somali', 'Amharic', 'Guarani', 'Maya', 'Apache languages', ' Ancient (to 1453)', 'Gallegan', 'Esperanto', 'Sign Languages', 'Hakka', 'Rajasthani', 'Aramaic', 'Bambara', 'Sindarin', 'Mohawk', 'Nepali', 'Berber languages', 'Lao', 'Tajik', 'Southern Sotho', 'Occitan', 'Kirghiz', 'Lingala', 'Egyptian (Ancient)', 'Cree', 'Old English', 'Burmese', 'Corsican', 'Scanian', 'Algonquin', 'More', 'Tzotzil', 'Sanskrit', 'Kannada', 'Sinhalese', 'Uzbek', 'Sardinian', 'Greenlandic', 'Crow', 'Creole', 'Kinyarwanda', 'British Sign Language', 'Syriac', 'Faroese', 'Russian Sign Language', 'Yoruba', 'Aymara', 'Tulu', 'Ladakhi', 'Acholi', 'Gumatj', 'Low German', 'Ungwatsi', 'Tatar', 'Norse', 'Japanese Sign Language', 'Cheyenne', 'Ladino', 'Tupi', 'Turkmen', 'Scots', 'Balinese', 'French Sign Language', 'Jola-Fonyi', 'Mende', 'Frisian', 'Haitian', ' Old', 'Assyrian Neo-Aramaic', 'Brazilian Sign Language', 'Shoshoni', 'Ibo', 'Dzongkha', 'Visayan', 'Ryukyuan', 'Belarusian', 'North American Indian', 'Kabyle', 'Fur', 'Songhay', 'Oriya', 'Athapascan languages', 'Konkani', 'Arapaho', 'Tigrigna', 'Samoan', 'Nyaneka', 'Assamese', 'Tok Pisin', 'Bhojpuri', 'Nama', 'Inupiaq', 'Maltese', 'Mari', 'Eastern Frisian', 'Tuvinian', 'Nyanja', 'Aidoukrou', 'Kuna', 'Awadhi', 'Creoles and pidgins', 'Tarahumara', 'Pawnee', 'Fulah', 'Peul', 'Indian Sign Language', 'Tswana', 'Washoe', 'Manipuri', 'Masai', 'Kabuverdianu', 'Spanish Sign Language', 'Shanxi', 'Hmong', 'Quenya', 'German Sign Language', 'Hassanya', 'Dyula', 'Breton', 'Karajè', 'Mapudungun', 'Abkhazian', 'Tonga', 'Middle English', 'Korean Sign Language', 'Purepecha', 'Kikuyu', 'Nenets', 'Ewe', 'Shona', 'Nahuatl', 'Uighur', 'Dinka', 'Cornish', 'Luxembourgish'],
    'Genre': ['Drama', 'Comedy', 'Romance', 'Crime', 'Thriller', 'Action', 'Adventure', 'Documentary', 'Horror', 'Biography', 'Family', 'Mystery', 'Fantasy', 'Sci-Fi', 'Animation', 'History', 'Music', 'War', 'Short', 'Musical', 'Sport', 'Western', 'Film-Noir', 'News', 'Talk-Show'],
    'Type': ['movie', 'series'],
    // 'Rating': ['English', 'Italian', 'French', 'Polish'],
    'Country': ['USA', 'UK', 'France', 'Germany', 'Canada', 'Italy', 'Japan', 'Spain', 'India', 'Australia', 'Sweden', 'Belgium', 'Hong Kong', 'Netherlands', 'Finland', 'Denmark', 'Russia', 'South Korea', 'China', 'West Germany', 'Poland', 'Switzerland', 'Brazil', 'Mexico', 'Ireland', 'Argentina', 'Norway', 'Soviet Union', 'Austria', 'Hungary', 'Greece', 'Israel', 'Czech Republic', 'Iran', 'Portugal', 'Turkey', 'New Zealand', 'Taiwan', 'Romania', 'South Africa', 'Thailand', 'Luxembourg', 'Iceland', 'Yugoslavia', 'Czechoslovakia', 'Chile', 'Philippines', 'Croatia', 'Colombia', 'Singapore', 'Bulgaria', 'Estonia', 'United Arab Emirates', 'Morocco', 'Serbia', 'Ukraine', 'Slovenia', 'Latvia', 'Indonesia', 'Lithuania', 'Slovakia', 'Egypt', 'Bosnia and Herzegovina', 'Kazakhstan', 'Cuba', 'Peru', 'Uruguay', 'Venezuela', 'Georgia', 'Palestine', 'Tunisia', 'Algeria', 'Republic of Macedonia', 'Pakistan', 'Senegal', 'Jordan', 'Iraq', 'Federal Republic of Yugoslavia', 'Qatar', 'Lebanon', 'Vietnam', 'Serbia and Montenegro', 'Malaysia', 'Afghanistan', 'Puerto Rico', 'Burkina Faso', 'Ecuador', 'Panama', 'Dominican Republic', 'Bolivia', 'Rwanda', 'Tanzania', 'Cambodia', 'Nepal', 'Malta', 'Chad', 'Kenya', 'Uzbekistan', 'Kyrgyzstan', 'Tajikistan', 'East Germany', 'Nigeria', 'Syria', 'Costa Rica', 'Mauritania', 'Haiti', 'Angola', 'Ethiopia', 'Liberia', 'Albania', 'North Korea', 'Cyprus', 'Paraguay', 'Ghana', 'Botswana', 'Isle Of Man', 'Liechtenstein', 'Papua New Guinea', 'Saudi Arabia', 'Jamaica', 'Sri Lanka', 'Bangladesh', 'Guatemala', 'Bhutan', 'Madagascar', 'Montenegro', 'Cameroon', 'Bahamas', 'Mongolia', 'Belarus', 'Mali', 'Kosovo', 'Armenia', 'Moldova', 'Congo', 'Zimbabwe', 'Martinique', 'Aruba', 'Cète d\'Ivoire', 'El Salvador', 'Trinidad and Tobago', 'Kuwait', 'Faroe Islands', 'Somalia', 'Samoa', 'Zaire', 'Macao', 'Micronesia', 'Burma', 'Brunei', 'Uganda', 'Gabon', 'Laos', 'Vanuatu', 'Monaco', 'The Democratic Republic Of Congo', 'Bermuda', 'Greenland'],
    'Rating': ['1+', '2+', '3+', '4+', '5+', '6+', '7+', '8+', '9+'],
}

export default Data;
